base_url = "https://about.bofe.app"

build_search_index = false
compile_sass = false
default_language = "en"
minify_html = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[translations]
lang-name = "English"

client-repository = "Client repository"
description = "With Bofe you can easily build kanban style boards for your projects, personal workflows, or just for fun."
download = "Download"
get-it-on-google-play = "Get it on Google Play"
go-to-source-code = "Go to source code"
go-to-web-app = "Go to web app"
home = "Home"
open-source = "Open Source"
open-source-description = "Bofe is completely open source and available under the AGPL v3 license."
or = "or"
privacy-policy = "Privacy Policy"
roadmap = "Roadmap"
server-repository = "Server repository"
tagline = "Kanban style boards"
terms-of-service = "Terms of Service"
version = "Version"

[languages.es.translations]
lang-name = "Español"

client-repository = "Repositorio del cliente"
description = "Con Bofe puedes crear facilmente tableros al estilo kanban para tus proyectos, flujos personales, o simplemente por diversión."
download = "Descargar"
get-it-on-google-play = "Obtenla en Google Play"
go-to-source-code = "Ir al código fuente"
go-to-web-app = "Ir a la web app"
home = "Inicio"
open-source = "Código Abierto"
open-source-description = "Bofe es completamente código abierto y está disponible bajo la licencia AGPL v3."
or = "o"
privacy-policy = "Política de Privacidad"
roadmap = "Roadmap"
server-repository = "Repositorio del servidor"
tagline = "Tableros al estilo kanban"
terms-of-service = "Términos de Servicio"
version = "Versión"

[extra]
version = "0.0.0-alpha.3"
